// ==UserScript==
// @name         Extremely BAD Adblock
// @version      1.9
// @description  Really bad and wont stop tracking very well but bypasses where real adblocks fail <3 | Based on generic attributes of ad elements, rather than advanced filterlists, and only deletes elements after loading the page rather than blocking them instantly (Has some false positives, but will work on every common website)
// @author       Kaid#0001
// @run-at       document-start
// @match        *://*/*
// ==/UserScript==

!function(){"use strict";let e,t=0,a=0;function o(e,t){let a=!1;return e.src&&e.src.toLowerCase().includes(t)&&(a=!0),e.id&&e.id.toLowerCase().includes(t)&&(a=!0),e.href&&"string"==typeof e.href&&e.href.toLowerCase().includes(t)&&(a=!0),e.srcdoc&&e.srcdoc.toLowerCase().includes(t)&&(a=!0),e.srcset&&e.srcset.toLowerCase().includes(t)&&(a=!0),e.getAttribute("class")&&e.getAttribute("class").toLowerCase().includes(t)&&(a=!0),a}!function r(){e=Array.from(document.all),e.forEach((e=>{(o(e,"advert")||o(e,"affiliate")||o(e,"doubleclick.net")||o(e,"adsense")||o(e,"tracker")||o(e,"interad")||o(e,"interstitial")||o(e,"google")&&o(e,"ad")&&!o(e,"captcha")&&!o(e,"login")||o(e,"bncloud")||o(e,"referral")||o(e,"refid")|o(e,"trafficjunky")||o(e,"pb_template")||o(e,"__clb"))&&(e.remove(),t++),e.innerHTML!=e.innerHTML.replace(/googletagmanager|google-analytics|googleanalytics|googleadservices|adwords|adsense|admob|urchin.com|doubleclick.net/gim,"thisIsAGoogleAd.invalid.url")&&(e.innerHTML=e.innerHTML.replace(/googletagmanager|google-analytics|googleanalytics|googleadservices|adwords|adsense|admob|urchin.com|doubleclick.net/gim,"thisIsAGoogleAd.invalid.url"),t++),e.src&&e.src!=e.src.replace(/googletagmanager|google-analytics|googleanalytics|googleadservices|adwords|adsense|admob|urchin.com|doubleclick.net/gim,"thisIsAGoogleAd.invalid.url")&&(e.src=e.src.replace(/googletagmanager|google-analytics|googleanalytics|googleadservices|adwords|adsense|admob|urchin.com|doubleclick.net/gim,"thisIsAGoogleAd.invalid.url"),t++)})),e=Array.from(document.getElementsByTagName("iframe")).concat(Array.from(document.getElementsByTagName("img"))).concat(Array.from(document.getElementsByTagName("a"))),e.forEach((e=>{e.getAttribute("data-jsarwt")&&(e.removeAttribute("data-jsarwt"),t++),(o(e,"banner")||"A"===e.tagName&&e.offsetHeight>120&&e.offsetWidth>1200)&&("NAV"===e.parentElement.tagName&&(e.parentElement.remove(),t++),e&&(e.remove(),t++))})),Array.from(document.getElementsByTagName("div")).forEach((e=>{e.getAttribute("class")&&e.getAttribute("class").toLowerCase().includes("adlinks")&&(e.parentElement.remove(),t++),e.getAttribute("class")&&e.getAttribute("class").toLowerCase().includes("ublock")&&Array.from(e.parentElement.children).forEach((e=>{e.getAttribute("class")&&e.getAttribute("class").toLowerCase().includes("hd")&&(e.remove(),t++)}))})),t>a&&(console.log("EBA: Blocked Items | "+t),a=t),setTimeout(r,400)}()}();
